version: '3.8'

services: 
    web:
        build: .
        command: python3 /home/mateusz/django_projects/m_portfolio/manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/home/mateusz/django_projects/m_portfolio
        ports: 
            - 8000:8000
        depends_on: 
            - db
    db:
        image: postgres:11
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_HOST=db
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
volumes: 
    postgres_data: